### ISSUE TITLE
Unrecognized element 'overhaul'

### ISSUE THREAD

**Issue by MintyHeal** [SucklessWindows/SucklessWindows#30]
![image](https://github.com/user-attachments/assets/b1c29260-5dbf-4335-8f6a-44592c0ad255)

**Comment by TheOnlyChuon** [comment]
Would be fixed in the next version

**Comment by TheOnlyChuon** [comment]
Fixed, thanks for your report 💗
The lastest version of SucklessWindows (4.2024.8) broke due to newest AME Wizard Beta build. If you are an advanced user, please follow [this guild](https://github.com/SucklessWindows/SucklessWindows?tab=readme-ov-file#%EF%B8%8F-build) and help us testing new changes. If any bug occurs, report it in our Discord server.
